# Generated by Django 4.2.2 on 2024-03-05 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AdminCredentials',
            fields=[
                ('admin_username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('admin_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=20)),
                ('branch', models.CharField(choices=[('COMPS', 'Computer Science'), ('IT', 'Information Technology'), ('EXTC', 'Electronics and Telecommunication'), ('ETRX', 'Electronics'), ('MECH', 'Mechanical')], max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('roll_number', models.PositiveBigIntegerField()),
                ('january', models.PositiveBigIntegerField(blank=True, null=True)),
                ('february', models.PositiveBigIntegerField(blank=True, null=True)),
                ('march', models.PositiveBigIntegerField(blank=True, null=True)),
                ('april', models.PositiveBigIntegerField(blank=True, null=True)),
                ('may', models.PositiveBigIntegerField(blank=True, null=True)),
                ('june', models.PositiveBigIntegerField(blank=True, null=True)),
                ('july', models.PositiveBigIntegerField(blank=True, null=True)),
                ('august', models.PositiveBigIntegerField(blank=True, null=True)),
                ('september', models.PositiveBigIntegerField(blank=True, null=True)),
                ('october', models.PositiveBigIntegerField(blank=True, null=True)),
                ('november', models.PositiveBigIntegerField(blank=True, null=True)),
                ('december', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('branch', models.CharField(choices=[('COMPS', 'Computer Science'), ('IT', 'Information Technology'), ('EXTC', 'Electronics and Telecommunication'), ('ETRX', 'Electronics'), ('MECH', 'Mechanical')], max_length=20)),
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('sem', models.IntegerField()),
                ('scheme_name', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
                ('hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseAllotment',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('faculty_abbreviation', models.CharField(max_length=20, unique=True)),
                ('staff_abbreviation', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('dept', models.CharField(choices=[('COMPS', 'Computer Science'), ('IT', 'Information Technology'), ('EXTC', 'Electronics and Telecommunication'), ('ETRX', 'Electronics'), ('MECH', 'Mechanical')], max_length=100)),
                ('employee_code', models.PositiveIntegerField(unique=True)),
                ('faculty_abbreviation', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_email', models.EmailField(max_length=100)),
                ('experience', models.PositiveIntegerField(null=True)),
                ('post', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=20)),
                ('branch', models.CharField(choices=[('COMPS', 'Computer Science'), ('IT', 'Information Technology'), ('EXTC', 'Electronics and Telecommunication'), ('ETRX', 'Electronics'), ('MECH', 'Mechanical')], max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('roll_number', models.PositiveBigIntegerField()),
                ('ise', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ia1', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ia2', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ia3', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ca', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ese', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tw', models.PositiveBigIntegerField(blank=True, null=True)),
                ('oral', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('dept', models.CharField(choices=[('COMPS', 'Computer Science'), ('IT', 'Information Technology'), ('EXTC', 'Electronics and Telecommunication'), ('ETRX', 'Electronics'), ('MECH', 'Mechanical')], max_length=100)),
                ('employee_code', models.PositiveIntegerField(unique=True)),
                ('staff_abbreviation', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_email', models.EmailField(max_length=100)),
                ('experience', models.PositiveIntegerField(null=True)),
                ('post', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('student_name', models.CharField(max_length=100)),
                ('roll_number', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('upload_file', models.FileField(upload_to='media/')),
                ('drive_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubAdminCredentials',
            fields=[
                ('sub_admin_username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sub_admin_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_branch', models.CharField(choices=[('COMPS', 'Computer Science'), ('IT', 'Information Technology'), ('EXTC', 'Electronics and Telecommunication'), ('ETRX', 'Electronics'), ('MECH', 'Mechanical')], max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('roll_number', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('student_contact_no', models.CharField(max_length=20)),
                ('parents_contact_no', models.CharField(max_length=20)),
                ('parent_email_id', models.EmailField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=20)),
                ('course_1', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('course_2', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('course_3', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('course_4', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('course_5', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('course_6', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('course_7', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('course_8', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('course_9', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('course_10', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('course_11', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('course_12', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('course_13', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('course_14', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('course_15', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('proctor_abbreviation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_handler.faculty')),
            ],
        ),
        migrations.AddConstraint(
            model_name='marks',
            constraint=models.UniqueConstraint(fields=('course_code', 'roll_number'), name='unique_marks_course_roll'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('course_code', 'roll_number'), name='unique_attendance_course_roll'),
        ),
    ]
