# Generated by Django 4.2.2 on 2023-07-08 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(choices=[('comps', 'Computer Science'), ('it', 'Information Technology'), ('extc', 'Electronics and Telecommunication'), ('etrx', 'Electronics'), ('mech', 'Mechanical')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('Dept', models.CharField(max_length=100)),
                ('Sem', models.IntegerField()),
                ('Scheme_name', models.CharField(max_length=100)),
                ('Credit', models.IntegerField()),
                ('Hours', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_handler.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('Dept', models.CharField(max_length=100)),
                ('Employee_code', models.CharField(max_length=100)),
                ('Faculty_name', models.CharField(max_length=100)),
                ('Employee_Abbreviation', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Faculty_email', models.EmailField(max_length=100)),
                ('Experience', models.PositiveIntegerField()),
                ('Post', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_handler.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('Dept', models.CharField(max_length=100)),
                ('Employee_code', models.CharField(max_length=100)),
                ('staff_name', models.CharField(max_length=100)),
                ('Employee_Abbreviation', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Staff_email', models.EmailField(max_length=100)),
                ('Experience', models.PositiveIntegerField()),
                ('Post', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_handler.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=4)),
                ('Course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_handler.course')),
                ('Faculty_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_handler.faculty')),
                ('Staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_handler.staff')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_handler.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('Roll_number', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('Student_contact_no', models.CharField(max_length=20)),
                ('Parents_contact_no', models.CharField(max_length=20)),
                ('Parent_email_id', models.EmailField(max_length=100)),
                ('Proctor_Abbreviation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_handler.faculty')),
                ('student_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_handler.branch')),
            ],
        ),
    ]
