# Generated by Django 4.2.2 on 2023-07-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_handler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Credit',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Dept',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Hours',
            new_name='hours',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Scheme_name',
            new_name='scheme_name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Sem',
            new_name='sem',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Parent_email_id',
            new_name='parent_email_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Parents_contact_no',
            new_name='parents_contact_no',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Proctor_Abbreviation',
            new_name='proctor_abbreviation',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Roll_number',
            new_name='roll_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Student_contact_no',
            new_name='student_contact_no',
        ),
        migrations.AlterField(
            model_name='course',
            name='branch',
            field=models.CharField(choices=[('Comps', 'Computer Science'), ('IT', 'Information Technology'), ('EXTC', 'Electronics and Telecommunication'), ('ETRX', 'Electronics'), ('MECH', 'Mechanical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='branch',
            field=models.CharField(choices=[('Comps', 'Computer Science'), ('IT', 'Information Technology'), ('EXTC', 'Electronics and Telecommunication'), ('ETRX', 'Electronics'), ('MECH', 'Mechanical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='branch',
            field=models.CharField(choices=[('Comps', 'Computer Science'), ('IT', 'Information Technology'), ('EXTC', 'Electronics and Telecommunication'), ('ETRX', 'Electronics'), ('MECH', 'Mechanical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_branch',
            field=models.CharField(choices=[('Comps', 'Computer Science'), ('IT', 'Information Technology'), ('EXTC', 'Electronics and Telecommunication'), ('ETRX', 'Electronics'), ('MECH', 'Mechanical')], max_length=20),
        ),
        migrations.DeleteModel(
            name='branch',
        ),
    ]
